pipeline:
  build:
    image: python:2.7
    commands:
      - pip install -r requirements.txt
      - sleep 150
      - python manage.py test
services:
  db:
    image: mariadb:10.1.21
    environment:
      - MYSQL_ROOT_PASSWORD=database
