pipeline:
  build:
    image: python:2.7
    commands:
      - pip install -r requirements.txt
      - echo $(nslookup db)
      - python manage.py test
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=database
